name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.FYBRIK_BOT_APP_ID }}
          private_key: ${{ secrets.FYBRIK_BOT_PRIVATE_KEY }}
          repository: ${{ github.repository }}
      - name: Slash Command Dispatch
        id: scd
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commands: |
            cherry-pick
          dispatch-type: workflow
          reactions: false
          static-args: |
            comment-id=${{ github.event.comment.id }}
            pull-request=${{ github.event.issue.number }}
      - name: Edit comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ steps.scd.outputs.error-message }}
          reaction-type: confused
